@extends('layout')

@section('content')
    @include('modules.okna_index')
    @include('modules.services')
    @include('modules.okno')
    @include('modules.optional')
    @include('modules.colors')
    @include('modules.payment')
    @include('modules.work_we')
    @include('modules.ruler')
    @include('modules.about_us')
    @include('modules.reviews')
    @include('modules.gallery')
    @include('modules.expert')
@endsection
